# Generated by Django 5.1.4 on 2024-12-26 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0002_hours_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hours',
            options={'ordering': ['hours']},
        ),
    ]
